language: java
branches:
  excludes:
    - develop
before_install:
  - wget http://dl.google.com/android/android-sdk_r21.1-linux.tgz 
  - tar -zxf android-sdk_r21.1-linux.tgz
  - cd android-sdk-linux
  - export ANDROID_HOME=$(pwd)
  - export PATH=${PATH}:${ANDROID_HOME}/tools
  - android update sdk --filter platform-tool,android-16 --no-ui --force
  - export PATH=${PATH}:${ANDROID_HOME}/platform-tools
  - adb
